config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :accounts do
    resources :reviews
    resources :articles
  end
  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
    validates :userName, presence: true, length: {minimum: 3}
    validates :password, presence: true, length: {minimum: 3}
    has_many :articles, dependent: :destroy
    has_many :reviews, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :account
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :account
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
    def new
        @account = Account.new
    end
    
    def index
        @accounts = Account.all
        @reviews = Review.all
        @articles = Article.all
    end
    
    def create
       
        @account = Account.new(account_params)
        @userName = @account.userName
        @password = @account.password
        if Account.exists?(userName: @userName)
            @account = Account.where(userName: @userName).take
            
            if @account.password.eql?(@password)
                @account_id = @account.id
                redirect_to account_path(@account_id)
            else
                flash[:notice] = "*Incorrect password"
                redirect_to new_account_path 
            end
        elsif @account.save
            #creates new record if not existing and redirects
            redirect_to @account
        else
            flash[:notice] = "*Username and/or password too short"
            redirect_to new_account_path
        end
    
    end
    
    def show
        @account = Account.find(params[:id])
        @account_id=@account.id
        
        @articles= Article.where(account_id: @account_id)
        @reviews = Review.where(account_id: @account_id)
        
       
    end
end

private
    def account_params
        params.require(:account).permit(:userName, :password)
    end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def new
        @article = Article.new
    end
    
    def create
        @account = Account.find(params[:account_id])
        #just for refrences as what to do @article = Article.find(params[:article_id])
        @article = @account.articles.create(article_params)
        #just for reference as what to do @comment = @article.comments.create(comment_params)
       
        if @article.save
            redirect_to account_article_path(@account.id, @account.articles, @article.id, id: @article.id)
            
        else
            render 'new'
        end
    end
    
    def show
        @account = Account.find(params[:account_id])
        @account_id = params[:account_id]
        @articles= Article.where(account_id: @account_id)
        @article = Article.find(params[:id])
        
    end
    
    def destroy
        @account = Account.find(params[:account_id])
        @account_id = params[:account_id]
        @articles= Article.where(account_id: @account_id)
        @article.destroy

        redirect_to accounts_path
    end
    
end
private
    def article_params
        params.required(:article).permit(:title, :mainText, :image, :tag1, :tag2, :tag3)
    end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def new
        @review = Review.new
        
    end
    
    def create
       @account = Account.find(params[:account_id])
        
        @review = @account.reviews.new(review_params)
        
        if @review.save
            
            puts @review.id    
            redirect_to account_review_path(@account.id, @account.reviews, @review.id, id: @review.id)
            
             #change to show page
        else
             render 'new'
            
        end
        
    end
    
    def show
        @account = Account.find(params[:account_id])
        @account_id=params[:account_id]
        @reviews= Review.where(account_id: @account_id)
        @review = Review.find(params[:id])
       
    end
    
    def destroy
        
        @account = Account.find(params[:account_id])
        @account_id = params[:account_id]
        @reviews= Review.where(account_id: @account_id)
        @review.destroy

        redirect_to accounts_path
    end
end

private
    def review_params
        params.required(:review).permit(:title, :mainText, :rating, :image, :tag1, :tag2, :tag3)
    end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @account = Account.all;
    @review = Review.all;
    
    
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accounts/index.html.erb
<body>
    <% if params[:content].eql?("Reviews") %>
    <h2>All Reviews</h4>
    <div>
        <p>
            <% @reviews.each do |review| %>
            <% @account = @accounts.where(id: review.account_id).take %> 
                <p>
                    <%= link_to review.title, account_review_path(review.account_id, @account.reviews, review.id, id: review.id) %>
                    <%= image_tag(review.image, size: "50x50") %>
                    <td class="rating"><%= review.rating.to_s %>/5.0 </td>
                    Author: <%= @account.userName %>
                </p>
            <% end %>
        </p>
    </div>
    <% end %>
    <% if params[:content].eql?("Articles") %>
    <h2>All Articles</h2>
     <div>
        <p>
            <% @articles.each do |article| %>
                <% @account = @accounts.where(id: article.account_id).take %>
                <p>
                    <%= link_to article.title, account_article_path(article.account_id, @account.articles, article.id, id: article.id) %>
                    <%= image_tag(article.image, size: "50x50") %>
                    Author: <%= @account.userName %>
                </p>
            <% end %>
        </p>
     </div>
     <% end %>
</body>

app/views/accounts/new.html.erb
<%= form_for @account do |f| %>
<h3 class = "mid_header">Choose a username and password</h3>
<% flash.each do |key, value| %>
    <p class="notice notice-<%= key %>"><%= value %></p>
<% end %>
<p>
    <%= f.label :userName %><br>
    <%= f.text_field :userName %>
</p>
<p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
</p>
<p>
    <%= f.submit "Login or Create Account"%>
</p>



<% end %>

app/views/accounts/show.html.erb
<h1 id="userHeader"> User: <%= @account.userName %> </h1>

<body>
     <div>
	
	<%= link_to "<button>Create Review</button>".html_safe, new_account_review_path(@account), :id=>"acctRev" ,:class=>"buttons" %>
	<%= link_to "<button>Create Article</button>".html_safe, new_account_article_path(@account), :id=>"acctArt" ,:class=>"buttons" %>
	</div>

	<p id="revP">
	   <h2>My Reviews </h2>
    <% @reviews.each do |review| %>
            <p>
            <td><%= link_to review.title, account_review_path(@account.id, @account.reviews,id: review.id) %></td>
            <%= image_tag(review.image, size: "50x50") %>
            <td class="rating"><%= review.rating.to_s %>/5.0 </td>
            </p>
	<% end %>
	</p>
	
	<p id="artP">
				
      <h2>My Articles </h2>
    <% @articles.each do |article| %>
            <p>
            <td><%= link_to article.title, account_article_path(@account.id, @account.articles,id: article.id) %></td>
            <%= image_tag(article.image, size: "50x50") %>
            </p>
            
	<% end %>
	</p>
	
    <p id="buttonP">
	    <%= link_to "<button>Logout</button>".html_safe, welcome_index_path , :id=>"", :class=>"buttons" %>
	</p>



</body>

app/views/articles/new.html.erb
<h4>NEW ARTICLE</h4>

<%= form_for :article, url: account_articles_path do |f| %>

<p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
</p>
 
<p>
    <%= f.label :mainText %><br>
    <%= f.text_area :mainText %>
</p>

<p>
    <%= f.label :image %><br>
    <%= f.text_field :image %>
</p>

<p>
    <%= f.label :tag1 %><br>
    <%= f.text_field :tag1 %>
</p>

<p>
    <%= f.label :tag2 %><br>
    <%= f.text_field :tag2 %>
</p>

<p>
    <%= f.label :tag3 %><br>
    <%= f.text_field :tag3 %>
</p>
 
<p>
    <%= f.submit %>
</p>

<% end %>

app/views/articles/show.html.erb
<% article = @article %>
        <h2 class="mid_header">
            <%= article.title %>
        </h2>
    
        <p>
            <%= image_tag(article.image, size: "300x200") %>
        </p>    
        <p class="mainText" >
            <%= article.mainText %>
        </p>
    
        <p class="tags">
            tags: <%= article.tag1 %>, <%= article.tag2 %>, <%= article.tag3 %>
        </p>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameRevs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1 id = "App_name" align =center >
	  Game Revs
	  
	  <div align = center>
	   <input id = "search_box" type = "text"  name = query width = "888" placeholder = "Search">
	   
	   </div>
	<div align = left>
<%= link_to "Home", welcome_index_path, {style: "font-size: 50px"} %>

</div>
	</h1>
    <%= yield %>
  </body>
</html>

app/views/layouts/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameRevs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/new.html.erb
<h4>NEW REVIEW</h4>

<%= form_for @review, url: account_reviews_path do |f| %>
<p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
</p>
 
<p>
    <%= f.label :mainText %><br>
    <%= f.text_area :mainText %>
</p>

<p>
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
</p>

<p>
    <%= f.label :image %><br>
    <%= f.text_field :image %>
</p>

<p>
    <%= f.label :tag1 %><br>
    <%= f.text_field :tag1 %>
</p>

<p>
    <%= f.label :tag2 %><br>
    <%= f.text_field :tag2 %>
</p>

<p>
    <%= f.label :tag3 %><br>
    <%= f.text_field :tag3 %>
</p>
 
<p>
    <%= f.submit %>
</p>

<% end %>

app/views/reviews/show.html.erb
<%review = @review %>
    
        <h2 class="mid_header">
            <%= review.title %>
        </h2>
    
        <p>
            <%= image_tag(review.image, size: "300x200") %>
        </p>    
        <p class="rating">
            <%= review.rating.to_s %>/5.0
        </p>
        <p class="mainText" >
            <%= review.mainText %>
        </p>
    
        <p class="tags">
            tags: <%= review.tag1 %>, <%= review.tag2 %>, <%= review.tag3 %>
        </p>
    

app/views/welcome/index.html.erb
<html lang = "en">

<head>
</head>

<body>
	<title >
		Game Revs
	</title>

	<div style >	
	<%= link_to "<button>Login/Sign-Up</button>".html_safe, new_account_path, :id=>"", :class=>"buttons" %>
	
	
	</div>
	
	<!-- Wrapper for the headers -->
	
	 <div style = "clear:both;">
		<h2 class="mid_header" style ="float:right; margin-right: 310px;">
		Articles
		</h2>
	
		<h3 class="mid_header" style = "float:left; margin-left: 308px;">
		Reviews
		<br/>
		</h3>
	</div>
	
	
	<!-- Wrapper for the buttons -->
	 <div style = "clear:both;">
		
		
		<%= link_to "<button>All Reviews </button>".html_safe, accounts_path(:content => "Reviews"), :id=>"allRevButton", :class=>"buttons" %>
		
		
		<%= link_to "<button>All Articles </button>".html_safe, accounts_path(:content => "Articles"), :id=>"allArtButton", :class=>"buttons" %>
		
		
	</div>
	<!--- Wrapper for the list of articles and reviews -->
	<div class="lists_top" style = "clear:both">
		<p1 class="list_trending" id = "articles_list" >
		Trending Articles
		<table>
            	<tr>
            		<th>Title</th>
		</tr>
		
             
        	<% @articles = Article.order('created_at DESC') %>    
            
            <% counter = 0 %>
             <% @articles.each do |article| %>
             <tr>
             	<% if counter < 10 %>
             	<% @accounts = Account.where(id: article.account_id).take %>
             
             	<%  account_id = @accounts.id %>
             	
           <td> <%= article.title %> </td>
            <td><%= link_to 'Show', account_article_path(account_id, @accounts.articles, article.id, id: article.id) %></td>
            	<% counter= counter +1 %>
            	<% else %>
            	<% break %>
            	<% end%>
            
            </tr>
            <% end%>
		 
		 </table> 
		</p1>

		<p2 class="list_trending" id ="reviews_list" style = "float:left;"  >
		Trending Reviews
		
			<table>
			<tr  >
            		<th>Title</th>
		</tr>
            	<tr>
            		<% @reviews = Review.order('created_at DESC') %>
            		
            		
            <% counter = 0 %>
             <% @reviews.each do |review| %>
             <tr>
             	<% if counter < 10 %>
             	<% @accounts = Account.where(id: review.account_id).take %>
             
             	<%  account_id = @accounts.id %>
             	
           <td> <%= review.title %> </td>
            <td><%= link_to 'Show',  account_review_path(@accounts.id, @accounts.reviews, review.id, id: review.id) %></td>
            	<% counter= counter +1 %>
            	<% else %>
            	<% break %>
            	<% end%>
            
            </tr>
            <% end%>

		 </table> 
		
		</p2>
	

		</p1>
	
	</div>
	
</body>